version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_bloodlink
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: BloodLink
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  pgdata: